/** Declaration file generated by dts-gen */

export function JSHINT(s: any, o: any, g: any): any;

export namespace JSHINT {
    // Circular reference from jshint.JSHINT
    const jshint: any;

    const prototype: {
    };

    function addModule(func: any): void;

    function data(): any;

    namespace addModule {
        const prototype: {
        };

    }

    namespace data {
        const prototype: {
        };

    }

}

