/** Declaration file generated by dts-gen */

export = mixin_deep;

declare function mixin_deep(target: any, objects: any, ...args: any[]): any;

declare namespace mixin_deep {
    const prototype: {
    };

}

