/** Declaration file generated by dts-gen */

export = hashring;

declare class hashring {
    constructor(servers: any, algorithm: any, options: any);

    add(servers: any): any;

    addServer(...args: any[]): any;

    continuum(): any;

    digest(key: any): any;

    end(): any;

    find(hashValue: any): any;

    get(key: any): any;

    getNode(...args: any[]): any;

    getNodePosition(...args: any[]): any;

    has(server: any): any;

    hash(key: any): any;

    hashValue(key: any): any;

    points(servers: any): any;

    position(...args: any[]): any;

    range(key: any, size: any, unique: any): any;

    remove(server: any): any;

    removeServer(...args: any[]): any;

    replace(...args: any[]): any;

    replaceServer(...args: any[]): any;

    reset(): any;

    swap(from: any, to: any): any;

    static version: string;

}


