/** Declaration file generated by dts-gen */

export = body_parser_xml;

declare function body_parser_xml(bodyParser: any): any;

declare namespace body_parser_xml {
    const prototype: {
    };

}

