/** Declaration file generated by dts-gen */

export = redis_cookie_store;

declare class redis_cookie_store {
    constructor(redisClient: any, id: any);

    findCookie(domain: any, path: any, cookieName: any, cb: any): void;

    findCookies(domain: any, path: any, cb: any): any;

    getKeyName(domain: any, path: any): any;

    putCookie(cookie: any, cb: any): void;

    removeCookie(domain: any, path: any, cookieName: any, cb: any): void;

    removeCookies(domain: any, path: any, cb: any): void;

    updateCookie(oldCookie: any, newCookie: any, cb: any): void;

}

